version: '3'
services:
  control:
    build: ./control
    image: control:1.0
    hostname: control
    expose:
     - 22
     - 80
    ports:
     - 2222:22
     - 8080:80
    volumes:
      - .:/home

  ubuntu:
    build: ./ubuntu
    image: ubuntu:1.0
    hostname: ubuntu
    expose:
     - 22
     - 80
    ports:
     - 2223:22
     - 8081:80
