FROM ubuntu

RUN apt-get update && apt-get install -y openssh-server

RUN apt-get install -y nano net-tools

RUN mkdir /var/run/sshd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

RUN apt-get install -y sudo

RUN sudo -i && echo 'root:password' | chpasswd

EXPOSE 22  80

CMD ["/usr/sbin/sshd", "-D"]
