

# Use a base image with the desired Linux distribution
FROM amazonlinux:latest

# Install OpenSSH server and update the package index
RUN yum -y update && \
    yum -y install openssh-server && \
	yum -y install sudo && \
    yum clean all

# Configure SSH
RUN ssh-keygen -A && \
    echo "PermitRootLogin yes"  >> /etc/ssh/sshd_config  && \
	sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
	

# Set a default password for the root user (CHANGE THIS PASSWORD!)
RUN echo "root:password" | chpasswd

# Expose port 22 for SSH connections
EXPOSE 22 80

# Start the SSH service when the container runs
CMD ["/usr/sbin/sshd", "-D"]

